name: Seed posts to database

on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_AUTH_TOKEN: ${{ secrets.DATABASE_AUTH_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
          cache: pnpm
      - run: pnpm install --dev
      - run: pnpm db:seed-stats
